export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const USER_SIGN_OUT = 'USER_SIGN_OUT'

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const ADD_FOLDER_REQUEST = 'ADD_FOLDER_REQUEST'
export const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS'
export const ADD_FOLDER_FAILURE = 'ADD_FOLDER_FAILURE'

export const LOAD_FOLDERS_REQUEST = 'LOAD_FOLDERS_REQUEST'
export const LOAD_FOLDERS_SUCCESS = 'LOAD_FOLDERS_SUCCESS'
export const LOAD_FOLDERS_FAILURE = 'LOAD_FOLDERS_FAILURE'

export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS'
